# -*- coding: utf-8 -*-
"""AIPscript.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNF3EUfqg5seXHzFwDgUuH6Z0eXIl1jq
"""

import subprocess
import os

os.system("tput setaf 1")

print("\t\tScript for Creating AIP\t\t\t")

os.system("tput setaf 7")
print("\t-------------------------------------------------")
print("Entering local device")
while True:
  print("
      1.Export Single AIP
      2.Export Hierarchy AIPs
      3.Exit")
      ch=int(input("Enter your choice: "))

      if ch==1:
        hld = input("Enter the Handle:")
        op1 = subprocess.call("sudo -u dspace /opt/dspace2/bin/dspace packager -d -t AIP -e dhruvalpatel333@gmail.com -i 10249/{} /opt/dspace2/AIP/{}.zip".format(hld,hld),shell=True)
        print ("Created files are: ",op1)
        op2 = subprocess.call("cd /opt/dspace2/AIP/ && zip archive.zip *.zip",shell=True)
        print ("Ziped files: ",op2)
      
      elif ch==2:
        hld = input("Enter the Handle:")
        op1 = subprocess.call("sudo -u dspace /opt/dspace2/bin/dspace packager -d -a -t AIP -e dhruvalpatel333@gmail.com -i 10249/{} /opt/dspace2/AIP/{}.zip".format(hld,hld),shell=True)
        print ("Created files are: ",op1)
        op2 = subprocess.call("cd /opt/dspace2/AIP/ && zip archive.zip *.zip",shell=True)
        print ("Ziped files: ",op2)

      elif ch==3:
        print ("Exit")
        exit()

  input("Press enter to continue: ")
  os.system("clear")